// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: common.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common metadata included with ticks to carry per-hop timestamps and IDs.
type TickMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange name, e.g. "binance", "coinbase", "kraken".
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Canonical symbol string, e.g. "BTC-USDT".
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Optional sequence id or unique id supplied by exchange (if available).
	SequenceId string `protobuf:"bytes,3,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	// Timestamp supplied by the exchange (event time) when available.
	TimestampExchange *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp_exchange,json=timestampExchange,proto3" json:"timestamp_exchange,omitempty"`
	// Timestamp when the ingestor received the tick (producer timestamp in design).
	TimestampIngestorReceived *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp_ingestor_received,json=timestampIngestorReceived,proto3" json:"timestamp_ingestor_received,omitempty"`
	// Any raw source identifier (e.g. websocket channel) useful for debugging.
	Source        string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickMeta) Reset() {
	*x = TickMeta{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickMeta) ProtoMessage() {}

func (x *TickMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickMeta.ProtoReflect.Descriptor instead.
func (*TickMeta) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *TickMeta) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TickMeta) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TickMeta) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *TickMeta) GetTimestampExchange() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampExchange
	}
	return nil
}

func (x *TickMeta) GetTimestampIngestorReceived() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampIngestorReceived
	}
	return nil
}

func (x *TickMeta) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rarbiter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x02\n" +
	"\bTickMeta\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vsequence_id\x18\x03 \x01(\tR\n" +
	"sequenceId\x12I\n" +
	"\x12timestamp_exchange\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11timestampExchange\x12Z\n" +
	"\x1btimestamp_ingestor_received\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x19timestampIngestorReceived\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06sourceB&Z$github.com/kiran/arbiter/proto;protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(*TickMeta)(nil),            // 0: arbiter.proto.TickMeta
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	1, // 0: arbiter.proto.TickMeta.timestamp_exchange:type_name -> google.protobuf.Timestamp
	1, // 1: arbiter.proto.TickMeta.timestamp_ingestor_received:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
