// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: normalized_tick.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Normalized, exchange-agnostic tick used by downstream consumers.
type NormalizedTick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange that provided this tick (kept for attribution).
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Canonical symbol, e.g. "BTC-USDT".
	Symbol string  `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid    float64 `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask    float64 `protobuf:"fixed64,4,opt,name=ask,proto3" json:"ask,omitempty"`
	// Exchange-provided timestamp (if present).
	TimestampExchange *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp_exchange,json=timestampExchange,proto3" json:"timestamp_exchange,omitempty"`
	// When the ingestor received the tick.
	TimestampReceived *timestamp.Timestamp `protobuf:"bytes,6,opt,name=timestamp_received,json=timestampReceived,proto3" json:"timestamp_received,omitempty"`
	// When the normalizer produced this normalized tick.
	TimestampNormalized *timestamp.Timestamp `protobuf:"bytes,7,opt,name=timestamp_normalized,json=timestampNormalized,proto3" json:"timestamp_normalized,omitempty"`
	// Ids for traceability back to raw messages.
	SourceSequenceId string `protobuf:"bytes,8,opt,name=source_sequence_id,json=sourceSequenceId,proto3" json:"source_sequence_id,omitempty"`
	RawTopic         string `protobuf:"bytes,9,opt,name=raw_topic,json=rawTopic,proto3" json:"raw_topic,omitempty"`
	// Optional additional metadata.
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedTick) Reset() {
	*x = NormalizedTick{}
	mi := &file_normalized_tick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedTick) ProtoMessage() {}

func (x *NormalizedTick) ProtoReflect() protoreflect.Message {
	mi := &file_normalized_tick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedTick.ProtoReflect.Descriptor instead.
func (*NormalizedTick) Descriptor() ([]byte, []int) {
	return file_normalized_tick_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedTick) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *NormalizedTick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *NormalizedTick) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *NormalizedTick) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *NormalizedTick) GetTimestampExchange() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampExchange
	}
	return nil
}

func (x *NormalizedTick) GetTimestampReceived() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampReceived
	}
	return nil
}

func (x *NormalizedTick) GetTimestampNormalized() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampNormalized
	}
	return nil
}

func (x *NormalizedTick) GetSourceSequenceId() string {
	if x != nil {
		return x.SourceSequenceId
	}
	return ""
}

func (x *NormalizedTick) GetRawTopic() string {
	if x != nil {
		return x.RawTopic
	}
	return ""
}

func (x *NormalizedTick) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_normalized_tick_proto protoreflect.FileDescriptor

const file_normalized_tick_proto_rawDesc = "" +
	"\n" +
	"\x15normalized_tick.proto\x12\rarbiter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\x9e\x04\n" +
	"\x0eNormalizedTick\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x04 \x01(\x01R\x03ask\x12I\n" +
	"\x12timestamp_exchange\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11timestampExchange\x12I\n" +
	"\x12timestamp_received\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11timestampReceived\x12M\n" +
	"\x14timestamp_normalized\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13timestampNormalized\x12,\n" +
	"\x12source_sequence_id\x18\b \x01(\tR\x10sourceSequenceId\x12\x1b\n" +
	"\traw_topic\x18\t \x01(\tR\brawTopic\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.arbiter.proto.NormalizedTick.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$github.com/kiran/arbiter/proto;protob\x06proto3"

var (
	file_normalized_tick_proto_rawDescOnce sync.Once
	file_normalized_tick_proto_rawDescData []byte
)

func file_normalized_tick_proto_rawDescGZIP() []byte {
	file_normalized_tick_proto_rawDescOnce.Do(func() {
		file_normalized_tick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_normalized_tick_proto_rawDesc), len(file_normalized_tick_proto_rawDesc)))
	})
	return file_normalized_tick_proto_rawDescData
}

var file_normalized_tick_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_normalized_tick_proto_goTypes = []any{
	(*NormalizedTick)(nil),      // 0: arbiter.proto.NormalizedTick
	nil,                         // 1: arbiter.proto.NormalizedTick.MetadataEntry
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_normalized_tick_proto_depIdxs = []int32{
	2, // 0: arbiter.proto.NormalizedTick.timestamp_exchange:type_name -> google.protobuf.Timestamp
	2, // 1: arbiter.proto.NormalizedTick.timestamp_received:type_name -> google.protobuf.Timestamp
	2, // 2: arbiter.proto.NormalizedTick.timestamp_normalized:type_name -> google.protobuf.Timestamp
	1, // 3: arbiter.proto.NormalizedTick.metadata:type_name -> arbiter.proto.NormalizedTick.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_normalized_tick_proto_init() }
func file_normalized_tick_proto_init() {
	if File_normalized_tick_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_normalized_tick_proto_rawDesc), len(file_normalized_tick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_normalized_tick_proto_goTypes,
		DependencyIndexes: file_normalized_tick_proto_depIdxs,
		MessageInfos:      file_normalized_tick_proto_msgTypes,
	}.Build()
	File_normalized_tick_proto = out.File
	file_normalized_tick_proto_goTypes = nil
	file_normalized_tick_proto_depIdxs = nil
}
