// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: raw_tick.proto

package proto

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Raw tick format as received from an exchange, minimally parsed and
// annotated with ingestor timestamps.
type RawTick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common metadata including exchange and symbol.
	Meta *TickMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The raw payload (JSON or binary) as received from the exchange, useful
	// for replay and debugging.
	RawPayload []byte `protobuf:"bytes,2,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	// Price fields when available. Some exchanges provide separate fields.
	Price  float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Bid    float64 `protobuf:"fixed64,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask    float64 `protobuf:"fixed64,5,opt,name=ask,proto3" json:"ask,omitempty"`
	Volume float64 `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	// Free-form metadata (key/value) for exchange-specific info.
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTick) Reset() {
	*x = RawTick{}
	mi := &file_raw_tick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTick) ProtoMessage() {}

func (x *RawTick) ProtoReflect() protoreflect.Message {
	mi := &file_raw_tick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTick.ProtoReflect.Descriptor instead.
func (*RawTick) Descriptor() ([]byte, []int) {
	return file_raw_tick_proto_rawDescGZIP(), []int{0}
}

func (x *RawTick) GetMeta() *TickMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RawTick) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *RawTick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RawTick) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *RawTick) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *RawTick) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *RawTick) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_raw_tick_proto protoreflect.FileDescriptor

const file_raw_tick_proto_rawDesc = "" +
	"\n" +
	"\x0eraw_tick.proto\x12\rarbiter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xa8\x02\n" +
	"\aRawTick\x12+\n" +
	"\x04meta\x18\x01 \x01(\v2\x17.arbiter.proto.TickMetaR\x04meta\x12\x1f\n" +
	"\vraw_payload\x18\x02 \x01(\fR\n" +
	"rawPayload\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\x01R\x03ask\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.arbiter.proto.RawTick.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$github.com/kiran/arbiter/proto;protob\x06proto3"

var (
	file_raw_tick_proto_rawDescOnce sync.Once
	file_raw_tick_proto_rawDescData []byte
)

func file_raw_tick_proto_rawDescGZIP() []byte {
	file_raw_tick_proto_rawDescOnce.Do(func() {
		file_raw_tick_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_tick_proto_rawDesc), len(file_raw_tick_proto_rawDesc)))
	})
	return file_raw_tick_proto_rawDescData
}

var file_raw_tick_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raw_tick_proto_goTypes = []any{
	(*RawTick)(nil),  // 0: arbiter.proto.RawTick
	nil,              // 1: arbiter.proto.RawTick.MetadataEntry
	(*TickMeta)(nil), // 2: arbiter.proto.TickMeta
}
var file_raw_tick_proto_depIdxs = []int32{
	2, // 0: arbiter.proto.RawTick.meta:type_name -> arbiter.proto.TickMeta
	1, // 1: arbiter.proto.RawTick.metadata:type_name -> arbiter.proto.RawTick.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raw_tick_proto_init() }
func file_raw_tick_proto_init() {
	if File_raw_tick_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_tick_proto_rawDesc), len(file_raw_tick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_tick_proto_goTypes,
		DependencyIndexes: file_raw_tick_proto_depIdxs,
		MessageInfos:      file_raw_tick_proto_msgTypes,
	}.Build()
	File_raw_tick_proto = out.File
	file_raw_tick_proto_goTypes = nil
	file_raw_tick_proto_depIdxs = nil
}
