// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: signal.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arbitrage signal schema emitted by the detector.
type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical symbol, e.g. "BTC-USDT".
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Where to buy and where to sell.
	BuyExchange  string  `protobuf:"bytes,2,opt,name=buy_exchange,json=buyExchange,proto3" json:"buy_exchange,omitempty"`
	SellExchange string  `protobuf:"bytes,3,opt,name=sell_exchange,json=sellExchange,proto3" json:"sell_exchange,omitempty"`
	BuyPrice     float64 `protobuf:"fixed64,4,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice    float64 `protobuf:"fixed64,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// sell_price - buy_price
	Spread float64 `protobuf:"fixed64,6,opt,name=spread,proto3" json:"spread,omitempty"`
	// Profit after fees/estimated costs.
	FeeAdjustedProfit float64 `protobuf:"fixed64,7,opt,name=fee_adjusted_profit,json=feeAdjustedProfit,proto3" json:"fee_adjusted_profit,omitempty"`
	// When the opportunity was observed/detected.
	TimestampOpportunity *timestamp.Timestamp `protobuf:"bytes,8,opt,name=timestamp_opportunity,json=timestampOpportunity,proto3" json:"timestamp_opportunity,omitempty"`
	// When the contributing tick(s) were received by the ingestor(s).
	TimestampTickReceived *timestamp.Timestamp `protobuf:"bytes,9,opt,name=timestamp_tick_received,json=timestampTickReceived,proto3" json:"timestamp_tick_received,omitempty"`
	// End-to-end latency measured in milliseconds from ingestor receive -> signal publish.
	LatencyMs int64 `protobuf:"varint,10,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Optional context for debugging: per-exchange timestamps, sequence ids, etc.
	Metadata map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional confidence/estimated volume to help filter signals.
	EstimatedVolume float64 `protobuf:"fixed64,12,opt,name=estimated_volume,json=estimatedVolume,proto3" json:"estimated_volume,omitempty"`
	Confidence      float64 `protobuf:"fixed64,13,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Signal) GetBuyExchange() string {
	if x != nil {
		return x.BuyExchange
	}
	return ""
}

func (x *Signal) GetSellExchange() string {
	if x != nil {
		return x.SellExchange
	}
	return ""
}

func (x *Signal) GetBuyPrice() float64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *Signal) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *Signal) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *Signal) GetFeeAdjustedProfit() float64 {
	if x != nil {
		return x.FeeAdjustedProfit
	}
	return 0
}

func (x *Signal) GetTimestampOpportunity() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampOpportunity
	}
	return nil
}

func (x *Signal) GetTimestampTickReceived() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampTickReceived
	}
	return nil
}

func (x *Signal) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Signal) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Signal) GetEstimatedVolume() float64 {
	if x != nil {
		return x.EstimatedVolume
	}
	return 0
}

func (x *Signal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_signal_proto protoreflect.FileDescriptor

const file_signal_proto_rawDesc = "" +
	"\n" +
	"\fsignal.proto\x12\rarbiter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x04\n" +
	"\x06Signal\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fbuy_exchange\x18\x02 \x01(\tR\vbuyExchange\x12#\n" +
	"\rsell_exchange\x18\x03 \x01(\tR\fsellExchange\x12\x1b\n" +
	"\tbuy_price\x18\x04 \x01(\x01R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x05 \x01(\x01R\tsellPrice\x12\x16\n" +
	"\x06spread\x18\x06 \x01(\x01R\x06spread\x12.\n" +
	"\x13fee_adjusted_profit\x18\a \x01(\x01R\x11feeAdjustedProfit\x12O\n" +
	"\x15timestamp_opportunity\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x14timestampOpportunity\x12R\n" +
	"\x17timestamp_tick_received\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x15timestampTickReceived\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\n" +
	" \x01(\x03R\tlatencyMs\x12?\n" +
	"\bmetadata\x18\v \x03(\v2#.arbiter.proto.Signal.MetadataEntryR\bmetadata\x12)\n" +
	"\x10estimated_volume\x18\f \x01(\x01R\x0festimatedVolume\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\x01R\n" +
	"confidence\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$github.com/kiran/arbiter/proto;protob\x06proto3"

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData []byte
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)))
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signal_proto_goTypes = []any{
	(*Signal)(nil),              // 0: arbiter.proto.Signal
	nil,                         // 1: arbiter.proto.Signal.MetadataEntry
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_signal_proto_depIdxs = []int32{
	2, // 0: arbiter.proto.Signal.timestamp_opportunity:type_name -> google.protobuf.Timestamp
	2, // 1: arbiter.proto.Signal.timestamp_tick_received:type_name -> google.protobuf.Timestamp
	1, // 2: arbiter.proto.Signal.metadata:type_name -> arbiter.proto.Signal.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
